spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: config-eureka-server-7001 #eureka服务端名称

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责是维护服务实例，不需要检索服务
    service-url:
    defaultZone: http://eureka7001.com:7001/eureka/

---
server:
  port: 7002
spring:
  profiles: test
  application:
    name: config-eureka-server-7002 #eureka服务端名称

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责是维护服务实例，不需要检索服务
    service-url:
    defaultZone: http://eureka7002.com:7002/eureka/